/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './index';
export const AmChartsModuleNgFactory:i0.NgModuleFactory<i1.AmChartsModule> = i0.ɵcmf(i1.AmChartsModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,
          i1.AmChartsService,i1.AmChartsService,[i0.NgZone]),i0.ɵmpd(512,i1.AmChartsModule,
          i1.AmChartsModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvcGF1YW4vV29yay9hbUNoYXJ0cy9hbWNoYXJ0czMtYW5ndWxhcjIvc3JjL2luZGV4Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL2hvbWUvcGF1YW4vV29yay9hbUNoYXJ0cy9hbWNoYXJ0czMtYW5ndWxhcjIvc3JjL2luZGV4LnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7OyJ9
